const authRouter = require('../auth/auth.router');
const adminRouterAdmin = require('../admin/admin.router.admin');
const bannerRouterAdmin = require('../banner/banner.router.admin');
const bannerRouterUser = require('../banner/banner.router.user');
const categoryRouterAdmin = require('../category/category.router.admin');
const categoryRouterUser = require('../category/category.router.user');
const chatRouterUser = require('../chat/chat.router.user');
const districtRouterUser = require('../district/district.router.user');
const districtRouterAdmin = require('../district/district.router.admin');
const evaluateRouterUser = require('../evaluate/evaluate.router.user');
const favoritePostRouterUser = require('../favorite-post/favoritePost.router.user');
const fileRouter = require('../file/file.router');
const followRouterUser = require('../follow/follow.router.user');
const historyClickRouterUser = require('../history-click/historyClick.router.user');
const historySearchRouterUser = require('../history-search/search.router.user');
const otpRouter = require('../otp/otp.router');
const paymentRouterAdmin = require('../payment/payment.router.admin');
const paymentRouterUser = require('../payment/payment.router.user');
const payosRouterUser = require('../payos/payos.router.user');
const perimissionRouterAdmin = require('../permission/permission.router.admin');
const postRouterAdmin = require('../post/post.router.admin');
const postRouterUser = require('../post/post.router.user');
const provinceRouterUser = require('../province/province.router.user');
const provinceRouterAdmin = require('../province/province.router.admin');
const qaChatBotRouterUser = require('../qa-chatbot/qaChatbot.router.user');
const qaChatBotRouterAdmin = require('../qa-chatbot/qaChatbot.router.admin');
const reportRouterAdmin = require('../report/report.router.admin');
const reportRouterUser = require('../report/report.router.user');
const roleRouterAdmin = require('../role/role.router.admin');
const sampleMessageRouterUser = require('../sample-message/sampleMessage.router.user');
const userRouterAdmin = require('../user/user.router.admin');
const userRouterUser = require('../user/user.router.user');
const wardRouterUser = require('../ward/ward.router.user');
const wardRouterAdmin = require('../ward/ward.router.admin');

const express = require('express');
const app = express();

app.use('/user/auth', authRouter);
app.use('/admin/auth', authRouter);
app.use('/admin/admin', adminRouterAdmin);
app.use('/admin/banner', bannerRouterAdmin);
app.use('/user/banner', bannerRouterUser);
app.use('/admin/category', categoryRouterAdmin);
app.use('/user/category', categoryRouterUser);
app.use('/user/chat', chatRouterUser);
app.use('/user/district', districtRouterUser);
app.use('/admin/district', districtRouterAdmin);
app.use('/user/evaluate', evaluateRouterUser);
app.use('/user/favorite-post', favoritePostRouterUser);
app.use('/file', fileRouter);
app.use('/user/follow', followRouterUser);
app.use('/user/history-click', historyClickRouterUser);
app.use('/user/history-search', historySearchRouterUser);
app.use('/otp', otpRouter);
app.use('/admin/payment', paymentRouterAdmin);
app.use('/user/payment', paymentRouterUser);
app.use('/user/payos', payosRouterUser);
app.use('/admin/permission', perimissionRouterAdmin);
app.use('/admin/post', postRouterAdmin);
app.use('/user/post', postRouterUser);
app.use('/user/province', provinceRouterUser);
app.use('/admin/province', provinceRouterAdmin);
app.use('/user/qa-chatbot', qaChatBotRouterUser);
app.use('/admin/qa-chatbot', qaChatBotRouterAdmin);
app.use('/admin/report', reportRouterAdmin);
app.use('/user/report', reportRouterUser);
app.use('/admin/role', roleRouterAdmin);
app.use('/user/sample-message', sampleMessageRouterUser);
app.use('/admin/user', userRouterAdmin);
app.use('/user/user', userRouterUser);
app.use('/user/ward', wardRouterUser);
app.use('/admin/ward', wardRouterAdmin);

module.exports = app;
