const authRouter = require('../auth/auth.router');
const categoryRouter = require('../category/category.router');
const otpRouter = require('../otp/otp.router');
const fileRouter = require('../file/file.router');
const permissionRouter = require('../permission/permission.router');
const provinceRouter = require('../province/province.router');
const districtRouter = require('../district/district.router');
const wardRouter = require('../ward/ward.router');
const roleRouter = require('../role/role.router');
const bannerRouter = require('../banner/banner.router');
const adminRouter = require('../admin/admin.router');
const userRouter = require('../user/user.router');
const postRouter = require('../post/post.router');
const evaluateRouter = require('../evaluate/evaluate.router');
const favoritePostRouter = require('../favorite-post/favoritePost.router');
const historyClickRouter = require('../history-click/historyClick.router');
const payOSRouter = require('../payos/payos.router');
const paymentRouter = require('../payment/payment.router');
const historySearchRouter = require('../history-search/search.router');
const followRouter = require('../follow/follow.router');
const chatRouter = require('../chat/chat.router');
const sampleMessageRouter = require('../sample-message/sampleMessage.router');
const express = require('express');
const app = express();

app.use('/auth/', authRouter);
app.use('/category/', categoryRouter);
app.use('/otp/', otpRouter);
app.use('/file/', fileRouter);
app.use('/permission/', permissionRouter);
app.use('/province/', provinceRouter);
app.use('/district/', districtRouter);
app.use('/ward/', wardRouter);
app.use('/role/', roleRouter);
app.use('/banner/', bannerRouter);
app.use('/admin/', adminRouter);
app.use('/user/', userRouter);
app.use('/post/', postRouter);
app.use('/evaluate/', evaluateRouter);
app.use('/favorite-post/', favoritePostRouter);
app.use('/history-click/', historyClickRouter);
app.use('/payos/', payOSRouter);
app.use('/payment/', paymentRouter);
app.use('/history-search/', historySearchRouter);
app.use('/follow/', followRouter);
app.use('/chat/', chatRouter);
app.use('/sample-message/', sampleMessageRouter);
module.exports = app;
