const express = require('express');
const categoryController = require('./category.controller');
const router = express.Router();
const { authJwt } = require('../../middlewares');
router.post('/', authJwt.accessToken, categoryController.createCategory);
router.get('/pagination', categoryController.fetchAllCategoriesWithPagination);
router.get('/', categoryController.fetchAllCategories);
router.get('/parent', categoryController.fetchCategoryParent);
router.get('/:id', authJwt.accessToken, categoryController.fetchCategoryById);
router.patch('/:id', authJwt.accessToken, categoryController.updateCategory);
router.delete('/:id', authJwt.accessToken, categoryController.deleteCategory);
module.exports = router;
